documentation:
  - changed-files:
      - any-glob-to-any-file: docs/content/**/*
explorer:
  - changed-files:
      - any-glob-to-any-file: apps/explorer/**/*
wallet:
  - changed-files:
      - any-glob-to-any-file: apps/wallet/**/*
wallet-dashboard:
  - changed-files:
      - any-glob-to-any-file: apps/wallet-dashboard/**/*
ts-sdk:
  - changed-files:
      - any-glob-to-any-file: sdk/**/*
apps-ui-kit:
  - changed-files:
      - any-glob-to-any-file: |
          - apps/ui-kit/**/*
          - apps/ui-icons/**/*
apps-backend:
  - changed-files:
      - any-glob-to-any-file: apps/apps-backend/**/*
evm-bridge:
  - changed-files:
      - any-glob-to-any-file: apps/evm-bridge/**/*
tooling:
  - changed-files:
      - any-glob-to-any-file: |
          sdk/**
          apps/**
          dapps/**
          packages/**
          build-scripts/**
          apps/names-display/**
          linting/**
          .husky/**
          .changeset/**
          .eslintrc.js
          .lintstagedrc.json
          .npmrc
          .prettierignore
          graphql.config.ts
          package.json
          pnpm-lock.yaml
          pnpm-workspace.yaml
          prettier.config.js
          turbo.json
          vercel.json
iota-names:
  - changed-files:
      - any-glob-to-any-file: |
          apps/names/**/*
          sdk/names/**/*
          packages/**/*
          apps/names-display/**/*
          build-scripts/**/*
ci:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
