// Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file iota/grpc/options.proto (package iota.grpc, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions, MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file iota/grpc/options.proto.
 */
export const file_iota_grpc_options: GenFile = /*@__PURE__*/
  fileDesc("Chdpb3RhL2dycGMvb3B0aW9ucy5wcm90bxIJaW90YS5ncnBjOlEKEW1lc3NhZ2VfYWNjZXNzb3JzEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGNCGAyABKAlSEG1lc3NhZ2VBY2Nlc3NvcnOIAQE6WgoWZmllbGRfbWFza190cmFuc3BhcmVudBIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxjShgMgASgIUhRmaWVsZE1hc2tUcmFuc3BhcmVudIgBATpLCg9maWVsZF9hY2Nlc3NvcnMSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGNGGAyABKAlSDmZpZWxkQWNjZXNzb3JziAEBYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * Default accessor types to generate for all fields in this message.
 * Valid values: getter, getter_opt, set, with, mut, mut_opt, all
 * Example: "with" generates with_field() for all fields
 * Field-level field_accessors annotations override this default.
 *
 * @generated from extension: optional string message_accessors = 50000;
 */
export const message_accessors: GenExtension<MessageOptions, string> = /*@__PURE__*/
  extDesc(file_iota_grpc_options, 0);

/**
 * When true, parent fields pointing to this message will skip this wrapper
 * layer in field_info (read_mask paths) and FieldPathBuilders. The wrapper
 * must contain exactly one repeated or map field.
 *
 * @generated from extension: optional bool field_mask_transparent = 50002;
 */
export const field_mask_transparent: GenExtension<MessageOptions, boolean> = /*@__PURE__*/
  extDesc(file_iota_grpc_options, 1);

/**
 * Comma-separated list of accessor types to generate for this field.
 * Valid values: getter, getter_opt, set, with, mut, mut_opt, all
 * Example: "set,with" generates set_field() and with_field()
 * Overrides message-level message_accessors option.
 *
 * @generated from extension: optional string field_accessors = 50001;
 */
export const field_accessors: GenExtension<FieldOptions, string> = /*@__PURE__*/
  extDesc(file_iota_grpc_options, 2);

