// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file iota/grpc/v1/checkpoint.proto (package iota.grpc.v1.checkpoint, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_iota_grpc_options } from "../options_pb.js";
import type { BcsData } from "./bcs_pb.js";
import { file_iota_grpc_v1_bcs } from "./bcs_pb.js";
import type { ValidatorAggregatedSignature } from "./signatures_pb.js";
import { file_iota_grpc_v1_signatures } from "./signatures_pb.js";
import type { Digest } from "./types_pb.js";
import { file_iota_grpc_v1_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file iota/grpc/v1/checkpoint.proto.
 */
export const file_iota_grpc_v1_checkpoint: GenFile = /*@__PURE__*/
  fileDesc("Ch1pb3RhL2dycGMvdjEvY2hlY2twb2ludC5wcm90bxIXaW90YS5ncnBjLnYxLmNoZWNrcG9pbnQijgEKEUNoZWNrcG9pbnRTdW1tYXJ5Ei8KBmRpZ2VzdBgBIAEoCzIaLmlvdGEuZ3JwYy52MS50eXBlcy5EaWdlc3RIAIgBARIrCgNiY3MYAiABKAsyGS5pb3RhLmdycGMudjEuYmNzLkJjc0RhdGFIAYgBAToIgrUYBHdpdGhCCQoHX2RpZ2VzdEIGCgRfYmNzIo8BChJDaGVja3BvaW50Q29udGVudHMSLwoGZGlnZXN0GAEgASgLMhouaW90YS5ncnBjLnYxLnR5cGVzLkRpZ2VzdEgAiAEBEisKA2JjcxgCIAEoCzIZLmlvdGEuZ3JwYy52MS5iY3MuQmNzRGF0YUgBiAEBOgiCtRgEd2l0aEIJCgdfZGlnZXN0QgYKBF9iY3MixAIKCkNoZWNrcG9pbnQSHAoPc2VxdWVuY2VfbnVtYmVyGAEgASgESACIAQESQAoHc3VtbWFyeRgCIAEoCzIqLmlvdGEuZ3JwYy52MS5jaGVja3BvaW50LkNoZWNrcG9pbnRTdW1tYXJ5SAGIAQESQgoIY29udGVudHMYAyABKAsyKy5pb3RhLmdycGMudjEuY2hlY2twb2ludC5DaGVja3BvaW50Q29udGVudHNIAogBARJNCglzaWduYXR1cmUYBCABKAsyNS5pb3RhLmdycGMudjEuc2lnbmF0dXJlcy5WYWxpZGF0b3JBZ2dyZWdhdGVkU2lnbmF0dXJlSAOIAQE6CIK1GAR3aXRoQhIKEF9zZXF1ZW5jZV9udW1iZXJCCgoIX3N1bW1hcnlCCwoJX2NvbnRlbnRzQgwKCl9zaWduYXR1cmViBnByb3RvMw", [file_iota_grpc_options, file_iota_grpc_v1_bcs, file_iota_grpc_v1_signatures, file_iota_grpc_v1_types]);

/**
 * A header for a checkpoint on the IOTA blockchain.
 *
 * On the IOTA network, checkpoints define the history of the blockchain. They are quite similar to
 * the concept of blocks used by other blockchains like Bitcoin or Ethereum. The IOTA blockchain,
 * however, forms checkpoints after transaction execution has already happened to provide a
 * certified history of the chain, instead of being formed before execution.
 *
 * Checkpoints commit to a variety of state, including but not limited to:
 * - The hash of the previous checkpoint.
 * - The set of transaction digests, their corresponding effects digests, as well as the set of
 *   user signatures that authorized its execution.
 * - The objects produced by a transaction.
 * - The set of live objects that make up the current state of the chain.
 * - On epoch transitions, the next validator committee.
 *
 * `CheckpointSummary`s themselves don't directly include all of the previous information but they
 * are the top-level type by which all the information is committed to transitively via cryptographic
 * hashes included in the summary. `CheckpointSummary`s are signed and certified by a quorum of
 * the validator committee in a given epoch to allow verification of the chain's state.
 *
 * @generated from message iota.grpc.v1.checkpoint.CheckpointSummary
 */
export type CheckpointSummary = Message<"iota.grpc.v1.checkpoint.CheckpointSummary"> & {
  /**
   * The digest of this CheckpointSummary.
   *
   * @generated from field: optional iota.grpc.v1.types.Digest digest = 1;
   */
  digest?: Digest | undefined;

  /**
   * This CheckpointSummary serialized as BCS.
   *
   * @generated from field: optional iota.grpc.v1.bcs.BcsData bcs = 2;
   */
  bcs?: BcsData | undefined;
};

/**
 * Describes the message iota.grpc.v1.checkpoint.CheckpointSummary.
 * Use `create(CheckpointSummarySchema)` to create a new message.
 */
export const CheckpointSummarySchema: GenMessage<CheckpointSummary> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_checkpoint, 0);

/**
 * The committed to contents of a checkpoint.
 *
 * @generated from message iota.grpc.v1.checkpoint.CheckpointContents
 */
export type CheckpointContents = Message<"iota.grpc.v1.checkpoint.CheckpointContents"> & {
  /**
   * The digest of this CheckpointContents.
   *
   * @generated from field: optional iota.grpc.v1.types.Digest digest = 1;
   */
  digest?: Digest | undefined;

  /**
   * This CheckpointContents serialized as BCS.
   *
   * @generated from field: optional iota.grpc.v1.bcs.BcsData bcs = 2;
   */
  bcs?: BcsData | undefined;
};

/**
 * Describes the message iota.grpc.v1.checkpoint.CheckpointContents.
 * Use `create(CheckpointContentsSchema)` to create a new message.
 */
export const CheckpointContentsSchema: GenMessage<CheckpointContents> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_checkpoint, 1);

/**
 * @generated from message iota.grpc.v1.checkpoint.Checkpoint
 */
export type Checkpoint = Message<"iota.grpc.v1.checkpoint.Checkpoint"> & {
  /**
   * The height of this checkpoint.
   *
   * @generated from field: optional uint64 sequence_number = 1;
   */
  sequenceNumber?: bigint | undefined;

  /**
   * The `CheckpointSummary` for this checkpoint.
   *
   * @generated from field: optional iota.grpc.v1.checkpoint.CheckpointSummary summary = 2;
   */
  summary?: CheckpointSummary | undefined;

  /**
   * The `CheckpointContents` for this checkpoint.
   *
   * @generated from field: optional iota.grpc.v1.checkpoint.CheckpointContents contents = 3;
   */
  contents?: CheckpointContents | undefined;

  /**
   * An aggregated quorum signature from the validator committee that
   * certified this checkpoint.
   *
   * @generated from field: optional iota.grpc.v1.signatures.ValidatorAggregatedSignature signature = 4;
   */
  signature?: ValidatorAggregatedSignature | undefined;
};

/**
 * Describes the message iota.grpc.v1.checkpoint.Checkpoint.
 * Use `create(CheckpointSchema)` to create a new message.
 */
export const CheckpointSchema: GenMessage<Checkpoint> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_checkpoint, 2);

