// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file iota/grpc/v1/command.proto (package iota.grpc.v1.command, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Value } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import { file_iota_grpc_options } from "../options_pb.js";
import type { BcsData } from "./bcs_pb.js";
import { file_iota_grpc_v1_bcs } from "./bcs_pb.js";
import type { TypeTag } from "./types_pb.js";
import { file_iota_grpc_v1_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file iota/grpc/v1/command.proto.
 */
export const file_iota_grpc_v1_command: GenFile = /*@__PURE__*/
  fileDesc("Chppb3RhL2dycGMvdjEvY29tbWFuZC5wcm90bxIUaW90YS5ncnBjLnYxLmNvbW1hbmQimAMKCEFyZ3VtZW50EjkKB3Vua25vd24YASABKAsyJi5pb3RhLmdycGMudjEuY29tbWFuZC5Bcmd1bWVudC5Vbmtub3duSAASOgoIZ2FzX2NvaW4YAiABKAsyJi5pb3RhLmdycGMudjEuY29tbWFuZC5Bcmd1bWVudC5HYXNDb2luSAASNQoFaW5wdXQYAyABKAsyJC5pb3RhLmdycGMudjEuY29tbWFuZC5Bcmd1bWVudC5JbnB1dEgAEjcKBnJlc3VsdBgEIAEoCzIlLmlvdGEuZ3JwYy52MS5jb21tYW5kLkFyZ3VtZW50LlJlc3VsdEgAGgkKB1Vua25vd24aCQoHR2FzQ29pbholCgVJbnB1dBISCgVpbmRleBgBIAEoDUgAiAEBQggKBl9pbmRleBpgCgZSZXN1bHQSEgoFaW5kZXgYASABKA1IAIgBARIgChNuZXN0ZWRfcmVzdWx0X2luZGV4GAIgASgNSAGIAQFCCAoGX2luZGV4QhYKFF9uZXN0ZWRfcmVzdWx0X2luZGV4QgYKBGtpbmQi/QEKDUNvbW1hbmRPdXRwdXQSNQoIYXJndW1lbnQYASABKAsyHi5pb3RhLmdycGMudjEuY29tbWFuZC5Bcmd1bWVudEgAiAEBEjIKCHR5cGVfdGFnGAIgASgLMhsuaW90YS5ncnBjLnYxLnR5cGVzLlR5cGVUYWdIAYgBARIrCgNiY3MYAyABKAsyGS5pb3RhLmdycGMudjEuYmNzLkJjc0RhdGFIAogBARIpCgRqc29uGAQgASgLMhYuZ29vZ2xlLnByb3RvYnVmLlZhbHVlSAOIAQFCCwoJX2FyZ3VtZW50QgsKCV90eXBlX3RhZ0IGCgRfYmNzQgcKBV9qc29uInQKDUlucHV0QXJndW1lbnQSKAoDYmNzGAEgASgLMhkuaW90YS5ncnBjLnYxLmJjcy5CY3NEYXRhSAASJgoEanNvbhgCIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZUgAOgiCtRgEd2l0aEIHCgVpbnB1dCJMCg5Db21tYW5kT3V0cHV0cxI0CgdvdXRwdXRzGAEgAygLMiMuaW90YS5ncnBjLnYxLmNvbW1hbmQuQ29tbWFuZE91dHB1dDoEkLUYASK5AQoNQ29tbWFuZFJlc3VsdBJBCg5tdXRhdGVkX2J5X3JlZhgBIAEoCzIkLmlvdGEuZ3JwYy52MS5jb21tYW5kLkNvbW1hbmRPdXRwdXRzSACIAQESQAoNcmV0dXJuX3ZhbHVlcxgCIAEoCzIkLmlvdGEuZ3JwYy52MS5jb21tYW5kLkNvbW1hbmRPdXRwdXRzSAGIAQFCEQoPX211dGF0ZWRfYnlfcmVmQhAKDl9yZXR1cm5fdmFsdWVzIkwKDkNvbW1hbmRSZXN1bHRzEjQKB3Jlc3VsdHMYASADKAsyIy5pb3RhLmdycGMudjEuY29tbWFuZC5Db21tYW5kUmVzdWx0OgSQtRgBYgZwcm90bzM", [file_google_protobuf_struct, file_iota_grpc_options, file_iota_grpc_v1_bcs, file_iota_grpc_v1_types]);

/**
 * An argument to a programmable transaction command.
 *
 * @generated from message iota.grpc.v1.command.Argument
 */
export type Argument = Message<"iota.grpc.v1.command.Argument"> & {
  /**
   * @generated from oneof iota.grpc.v1.command.Argument.kind
   */
  kind: {
    /**
     * @generated from field: iota.grpc.v1.command.Argument.Unknown unknown = 1;
     */
    value: Argument_Unknown;
    case: "unknown";
  } | {
    /**
     * @generated from field: iota.grpc.v1.command.Argument.GasCoin gas_coin = 2;
     */
    value: Argument_GasCoin;
    case: "gasCoin";
  } | {
    /**
     * @generated from field: iota.grpc.v1.command.Argument.Input input = 3;
     */
    value: Argument_Input;
    case: "input";
  } | {
    /**
     * @generated from field: iota.grpc.v1.command.Argument.Result result = 4;
     */
    value: Argument_Result;
    case: "result";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message iota.grpc.v1.command.Argument.
 * Use `create(ArgumentSchema)` to create a new message.
 */
export const ArgumentSchema: GenMessage<Argument> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 0);

/**
 * Unknown Argument kind.
 *
 * @generated from message iota.grpc.v1.command.Argument.Unknown
 */
export type Argument_Unknown = Message<"iota.grpc.v1.command.Argument.Unknown"> & {
};

/**
 * Describes the message iota.grpc.v1.command.Argument.Unknown.
 * Use `create(Argument_UnknownSchema)` to create a new message.
 */
export const Argument_UnknownSchema: GenMessage<Argument_Unknown> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 0, 0);

/**
 * The gas coin.
 *
 * @generated from message iota.grpc.v1.command.Argument.GasCoin
 */
export type Argument_GasCoin = Message<"iota.grpc.v1.command.Argument.GasCoin"> & {
};

/**
 * Describes the message iota.grpc.v1.command.Argument.GasCoin.
 * Use `create(Argument_GasCoinSchema)` to create a new message.
 */
export const Argument_GasCoinSchema: GenMessage<Argument_GasCoin> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 0, 1);

/**
 * One of the input objects or primitive values
 * (from `ProgrammableTransaction` inputs).
 *
 * @generated from message iota.grpc.v1.command.Argument.Input
 */
export type Argument_Input = Message<"iota.grpc.v1.command.Argument.Input"> & {
  /**
   * Index of an input when `kind` is `Input`.
   *
   * @generated from field: optional uint32 index = 1;
   */
  index?: number | undefined;
};

/**
 * Describes the message iota.grpc.v1.command.Argument.Input.
 * Use `create(Argument_InputSchema)` to create a new message.
 */
export const Argument_InputSchema: GenMessage<Argument_Input> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 0, 2);

/**
 * The result of another command (from `ProgrammableTransaction` commands).
 *
 * @generated from message iota.grpc.v1.command.Argument.Result
 */
export type Argument_Result = Message<"iota.grpc.v1.command.Argument.Result"> & {
  /**
   * Index of a result when `kind` is `Result`.
   *
   * @generated from field: optional uint32 index = 1;
   */
  index?: number | undefined;

  /**
   * Used to access a nested result when `kind` is `Result`.
   *
   * @generated from field: optional uint32 nested_result_index = 2;
   */
  nestedResultIndex?: number | undefined;
};

/**
 * Describes the message iota.grpc.v1.command.Argument.Result.
 * Use `create(Argument_ResultSchema)` to create a new message.
 */
export const Argument_ResultSchema: GenMessage<Argument_Result> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 0, 3);

/**
 * @generated from message iota.grpc.v1.command.CommandOutput
 */
export type CommandOutput = Message<"iota.grpc.v1.command.CommandOutput"> & {
  /**
   * @generated from field: optional iota.grpc.v1.command.Argument argument = 1;
   */
  argument?: Argument | undefined;

  /**
   * @generated from field: optional iota.grpc.v1.types.TypeTag type_tag = 2;
   */
  typeTag?: TypeTag | undefined;

  /**
   * @generated from field: optional iota.grpc.v1.bcs.BcsData bcs = 3;
   */
  bcs?: BcsData | undefined;

  /**
   * @generated from field: optional google.protobuf.Value json = 4;
   */
  json?: Value | undefined;
};

/**
 * Describes the message iota.grpc.v1.command.CommandOutput.
 * Use `create(CommandOutputSchema)` to create a new message.
 */
export const CommandOutputSchema: GenMessage<CommandOutput> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 1);

/**
 * A value passed to a Move function, in either encoding. The input counterpart
 * of `CommandOutput`.
 *
 * @generated from message iota.grpc.v1.command.InputArgument
 */
export type InputArgument = Message<"iota.grpc.v1.command.InputArgument"> & {
  /**
   * @generated from oneof iota.grpc.v1.command.InputArgument.input
   */
  input: {
    /**
     * The argument as BCS-encoded bytes.
     *
     * @generated from field: iota.grpc.v1.bcs.BcsData bcs = 1;
     */
    value: BcsData;
    case: "bcs";
  } | {
    /**
     * The argument as JSON, for the node to encode against the parameter's Move
     * type. `Value` holds numbers as doubles, which cannot represent every
     * integer, so numbers must go as strings.
     *
     * @generated from field: google.protobuf.Value json = 2;
     */
    value: Value;
    case: "json";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message iota.grpc.v1.command.InputArgument.
 * Use `create(InputArgumentSchema)` to create a new message.
 */
export const InputArgumentSchema: GenMessage<InputArgument> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 2);

/**
 * @generated from message iota.grpc.v1.command.CommandOutputs
 */
export type CommandOutputs = Message<"iota.grpc.v1.command.CommandOutputs"> & {
  /**
   * @generated from field: repeated iota.grpc.v1.command.CommandOutput outputs = 1;
   */
  outputs: CommandOutput[];
};

/**
 * Describes the message iota.grpc.v1.command.CommandOutputs.
 * Use `create(CommandOutputsSchema)` to create a new message.
 */
export const CommandOutputsSchema: GenMessage<CommandOutputs> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 3);

/**
 * An intermediate result/output from the execution of a single command
 *
 * @generated from message iota.grpc.v1.command.CommandResult
 */
export type CommandResult = Message<"iota.grpc.v1.command.CommandResult"> & {
  /**
   * @generated from field: optional iota.grpc.v1.command.CommandOutputs mutated_by_ref = 1;
   */
  mutatedByRef?: CommandOutputs | undefined;

  /**
   * @generated from field: optional iota.grpc.v1.command.CommandOutputs return_values = 2;
   */
  returnValues?: CommandOutputs | undefined;
};

/**
 * Describes the message iota.grpc.v1.command.CommandResult.
 * Use `create(CommandResultSchema)` to create a new message.
 */
export const CommandResultSchema: GenMessage<CommandResult> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 4);

/**
 * @generated from message iota.grpc.v1.command.CommandResults
 */
export type CommandResults = Message<"iota.grpc.v1.command.CommandResults"> & {
  /**
   * @generated from field: repeated iota.grpc.v1.command.CommandResult results = 1;
   */
  results: CommandResult[];
};

/**
 * Describes the message iota.grpc.v1.command.CommandResults.
 * Use `create(CommandResultsSchema)` to create a new message.
 */
export const CommandResultsSchema: GenMessage<CommandResults> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_command, 5);

