// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file iota/grpc/v1/dynamic_field.proto (package iota.grpc.v1.dynamic_field, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_iota_grpc_options } from "../options_pb.js";
import type { BcsData } from "./bcs_pb.js";
import { file_iota_grpc_v1_bcs } from "./bcs_pb.js";
import type { Object$ } from "./object_pb.js";
import { file_iota_grpc_v1_object } from "./object_pb.js";
import type { ObjectId } from "./types_pb.js";
import { file_iota_grpc_v1_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file iota/grpc/v1/dynamic_field.proto.
 */
export const file_iota_grpc_v1_dynamic_field: GenFile = /*@__PURE__*/
  fileDesc("CiBpb3RhL2dycGMvdjEvZHluYW1pY19maWVsZC5wcm90bxIaaW90YS5ncnBjLnYxLmR5bmFtaWNfZmllbGQipgUKDER5bmFtaWNGaWVsZBJMCgRraW5kGAEgASgOMjkuaW90YS5ncnBjLnYxLmR5bmFtaWNfZmllbGQuRHluYW1pY0ZpZWxkLkR5bmFtaWNGaWVsZEtpbmRIAIgBARIxCgZwYXJlbnQYAiABKAsyHC5pb3RhLmdycGMudjEudHlwZXMuT2JqZWN0SWRIAYgBARIzCghmaWVsZF9pZBgDIAEoCzIcLmlvdGEuZ3JwYy52MS50eXBlcy5PYmplY3RJZEgCiAEBEjYKDGZpZWxkX29iamVjdBgEIAEoCzIbLmlvdGEuZ3JwYy52MS5vYmplY3QuT2JqZWN0SAOIAQESLAoEbmFtZRgFIAEoCzIZLmlvdGEuZ3JwYy52MS5iY3MuQmNzRGF0YUgEiAEBEi0KBXZhbHVlGAYgASgLMhkuaW90YS5ncnBjLnYxLmJjcy5CY3NEYXRhSAWIAQESFwoKdmFsdWVfdHlwZRgHIAEoCUgGiAEBEjMKCGNoaWxkX2lkGAggASgLMhwuaW90YS5ncnBjLnYxLnR5cGVzLk9iamVjdElkSAeIAQESNgoMY2hpbGRfb2JqZWN0GAkgASgLMhsuaW90YS5ncnBjLnYxLm9iamVjdC5PYmplY3RICIgBASJJChBEeW5hbWljRmllbGRLaW5kEh4KGkRZTkFNSUNfRklFTERfS0lORF9VTktOT1dOEAASCQoFRklFTEQQARIKCgZPQkpFQ1QQAjoIgrUYBHdpdGhCBwoFX2tpbmRCCQoHX3BhcmVudEILCglfZmllbGRfaWRCDwoNX2ZpZWxkX29iamVjdEIHCgVfbmFtZUIICgZfdmFsdWVCDQoLX3ZhbHVlX3R5cGVCCwoJX2NoaWxkX2lkQg8KDV9jaGlsZF9vYmplY3RiBnByb3RvMw", [file_iota_grpc_options, file_iota_grpc_v1_bcs, file_iota_grpc_v1_object, file_iota_grpc_v1_types]);

/**
 * @generated from message iota.grpc.v1.dynamic_field.DynamicField
 */
export type DynamicField = Message<"iota.grpc.v1.dynamic_field.DynamicField"> & {
  /**
   * @generated from field: optional iota.grpc.v1.dynamic_field.DynamicField.DynamicFieldKind kind = 1;
   */
  kind?: DynamicField_DynamicFieldKind | undefined;

  /**
   * ObjectId of this dynamic field's parent.
   *
   * @generated from field: optional iota.grpc.v1.types.ObjectId parent = 2;
   */
  parent?: ObjectId | undefined;

  /**
   * ObjectId of this dynamic field.
   *
   * @generated from field: optional iota.grpc.v1.types.ObjectId field_id = 3;
   */
  fieldId?: ObjectId | undefined;

  /**
   * The field object itself
   *
   * @generated from field: optional iota.grpc.v1.object.Object field_object = 4;
   */
  fieldObject?: Object$ | undefined;

  /**
   * The dynamic field's "name"
   *
   * @generated from field: optional iota.grpc.v1.bcs.BcsData name = 5;
   */
  name?: BcsData | undefined;

  /**
   * The dynamic field's "value".
   *
   * For regular dynamic fields this contains the BCS-encoded value whose type
   * is given by `value_type`. For dynamic *object* fields this contains the
   * BCS-encoded ObjectID of the child object; use `child_object` to access the
   * full object.
   *
   * @generated from field: optional iota.grpc.v1.bcs.BcsData value = 6;
   */
  value?: BcsData | undefined;

  /**
   * The type of the dynamic field "value".
   *
   * For regular dynamic fields this is the Move type of the value stored
   * in the `value` field. For dynamic *object* fields this is the Move type
   * of the child object itself (e.g. `0x2::coin::Coin<0x2::iota::IOTA>`),
   * not `0x2::object::ID` — clients should use `child_object` rather than
   * BCS-decoding `value` with this type.
   *
   * @generated from field: optional string value_type = 7;
   */
  valueType?: string | undefined;

  /**
   * The ObjectId of the child object when a child is a dynamic
   * object field.
   *
   * The presence or absence of this field can be used to determine if a child
   * is a dynamic field or a dynamic child object
   *
   * @generated from field: optional iota.grpc.v1.types.ObjectId child_id = 8;
   */
  childId?: ObjectId | undefined;

  /**
   * The object itself when a child is a dynamic object field.
   *
   * @generated from field: optional iota.grpc.v1.object.Object child_object = 9;
   */
  childObject?: Object$ | undefined;
};

/**
 * Describes the message iota.grpc.v1.dynamic_field.DynamicField.
 * Use `create(DynamicFieldSchema)` to create a new message.
 */
export const DynamicFieldSchema: GenMessage<DynamicField> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_dynamic_field, 0);

/**
 * @generated from enum iota.grpc.v1.dynamic_field.DynamicField.DynamicFieldKind
 */
export enum DynamicField_DynamicFieldKind {
  /**
   * @generated from enum value: DYNAMIC_FIELD_KIND_UNKNOWN = 0;
   */
  DYNAMIC_FIELD_KIND_UNKNOWN = 0,

  /**
   * @generated from enum value: FIELD = 1;
   */
  FIELD = 1,

  /**
   * @generated from enum value: OBJECT = 2;
   */
  OBJECT = 2,
}

/**
 * Describes the enum iota.grpc.v1.dynamic_field.DynamicField.DynamicFieldKind.
 */
export const DynamicField_DynamicFieldKindSchema: GenEnum<DynamicField_DynamicFieldKind> = /*@__PURE__*/
  enumDesc(file_iota_grpc_v1_dynamic_field, 0, 0);

