// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2026 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file iota/grpc/v1/move_package_service.proto (package iota.grpc.v1.move_package_service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_iota_grpc_options } from "../options_pb.js";
import type { ObjectId } from "./types_pb.js";
import { file_iota_grpc_v1_types } from "./types_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file iota/grpc/v1/move_package_service.proto.
 */
export const file_iota_grpc_v1_move_package_service: GenFile = /*@__PURE__*/
  fileDesc("Cidpb3RhL2dycGMvdjEvbW92ZV9wYWNrYWdlX3NlcnZpY2UucHJvdG8SIWlvdGEuZ3JwYy52MS5tb3ZlX3BhY2thZ2Vfc2VydmljZSL6AQoaTGlzdFBhY2thZ2VWZXJzaW9uc1JlcXVlc3QSNQoKcGFja2FnZV9pZBgBIAEoCzIcLmlvdGEuZ3JwYy52MS50eXBlcy5PYmplY3RJZEgAiAEBEhYKCXBhZ2Vfc2l6ZRgCIAEoDUgBiAEBEhcKCnBhZ2VfdG9rZW4YAyABKAxIAogBARIjChZtYXhfbWVzc2FnZV9zaXplX2J5dGVzGAQgASgNSAOIAQE6CIK1GAR3aXRoQg0KC19wYWNrYWdlX2lkQgwKCl9wYWdlX3NpemVCDQoLX3BhZ2VfdG9rZW5CGQoXX21heF9tZXNzYWdlX3NpemVfYnl0ZXMingEKG0xpc3RQYWNrYWdlVmVyc2lvbnNSZXNwb25zZRJDCgh2ZXJzaW9ucxgBIAMoCzIxLmlvdGEuZ3JwYy52MS5tb3ZlX3BhY2thZ2Vfc2VydmljZS5QYWNrYWdlVmVyc2lvbhIcCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAxIAIgBAToIgrUYBHdpdGhCEgoQX25leHRfcGFnZV90b2tlbiLKAQoOUGFja2FnZVZlcnNpb24SNgoLb3JpZ2luYWxfaWQYASABKAsyHC5pb3RhLmdycGMudjEudHlwZXMuT2JqZWN0SWRIAIgBARI1CgpzdG9yYWdlX2lkGAIgASgLMhwuaW90YS5ncnBjLnYxLnR5cGVzLk9iamVjdElkSAGIAQESFAoHdmVyc2lvbhgDIAEoBEgCiAEBOgiCtRgEd2l0aEIOCgxfb3JpZ2luYWxfaWRCDQoLX3N0b3JhZ2VfaWRCCgoIX3ZlcnNpb24yqwEKEk1vdmVQYWNrYWdlU2VydmljZRKUAQoTTGlzdFBhY2thZ2VWZXJzaW9ucxI9LmlvdGEuZ3JwYy52MS5tb3ZlX3BhY2thZ2Vfc2VydmljZS5MaXN0UGFja2FnZVZlcnNpb25zUmVxdWVzdBo+LmlvdGEuZ3JwYy52MS5tb3ZlX3BhY2thZ2Vfc2VydmljZS5MaXN0UGFja2FnZVZlcnNpb25zUmVzcG9uc2ViBnByb3RvMw", [file_iota_grpc_options, file_iota_grpc_v1_types]);

/**
 * @generated from message iota.grpc.v1.move_package_service.ListPackageVersionsRequest
 */
export type ListPackageVersionsRequest = Message<"iota.grpc.v1.move_package_service.ListPackageVersionsRequest"> & {
  /**
   * Required. Either the `storage_id` of any version of an upgraded package,
   * or the `original_id` of an immutable (first version) package.
   *
   * @generated from field: optional iota.grpc.v1.types.ObjectId package_id = 1;
   */
  packageId?: ObjectId | undefined;

  /**
   * The maximum number of versions to return. The service may return fewer than this value.
   * If unspecified, at most `1000` entries will be returned.
   * The maximum value is `10000`; values above `10000` will be coerced to `10000`.
   *
   * @generated from field: optional uint32 page_size = 2;
   */
  pageSize?: number | undefined;

  /**
   * A page token, received from a previous `ListPackageVersions` call.
   * Provide this to retrieve the subsequent page.
   *
   * When paginating, all other parameters provided to `ListPackageVersions` must
   * match the call that provided the page token.
   *
   * @generated from field: optional bytes page_token = 3;
   */
  pageToken?: Uint8Array | undefined;

  /**
   * Optional maximum message size the client can receive (1MB - 128MB).
   * If not specified, server uses default chunking threshold (4MB).
   *
   * @generated from field: optional uint32 max_message_size_bytes = 4;
   */
  maxMessageSizeBytes?: number | undefined;
};

/**
 * Describes the message iota.grpc.v1.move_package_service.ListPackageVersionsRequest.
 * Use `create(ListPackageVersionsRequestSchema)` to create a new message.
 */
export const ListPackageVersionsRequestSchema: GenMessage<ListPackageVersionsRequest> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_move_package_service, 0);

/**
 * @generated from message iota.grpc.v1.move_package_service.ListPackageVersionsResponse
 */
export type ListPackageVersionsResponse = Message<"iota.grpc.v1.move_package_service.ListPackageVersionsResponse"> & {
  /**
   * List of all package versions, ordered by version.
   *
   * @generated from field: repeated iota.grpc.v1.move_package_service.PackageVersion versions = 1;
   */
  versions: PackageVersion[];

  /**
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   *
   * @generated from field: optional bytes next_page_token = 2;
   */
  nextPageToken?: Uint8Array | undefined;
};

/**
 * Describes the message iota.grpc.v1.move_package_service.ListPackageVersionsResponse.
 * Use `create(ListPackageVersionsResponseSchema)` to create a new message.
 */
export const ListPackageVersionsResponseSchema: GenMessage<ListPackageVersionsResponse> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_move_package_service, 1);

/**
 * A simplified representation of a package version.
 *
 * @generated from message iota.grpc.v1.move_package_service.PackageVersion
 */
export type PackageVersion = Message<"iota.grpc.v1.move_package_service.PackageVersion"> & {
  /**
   * The original (immutable) package ID shared across all versions
   *
   * @generated from field: optional iota.grpc.v1.types.ObjectId original_id = 1;
   */
  originalId?: ObjectId | undefined;

  /**
   * The storage ID of this specific package version
   *
   * @generated from field: optional iota.grpc.v1.types.ObjectId storage_id = 2;
   */
  storageId?: ObjectId | undefined;

  /**
   * The version number
   *
   * @generated from field: optional uint64 version = 3;
   */
  version?: bigint | undefined;
};

/**
 * Describes the message iota.grpc.v1.move_package_service.PackageVersion.
 * Use `create(PackageVersionSchema)` to create a new message.
 */
export const PackageVersionSchema: GenMessage<PackageVersion> = /*@__PURE__*/
  messageDesc(file_iota_grpc_v1_move_package_service, 2);

/**
 * @generated from service iota.grpc.v1.move_package_service.MovePackageService
 */
export const MovePackageService: GenService<{
  /**
   * @generated from rpc iota.grpc.v1.move_package_service.MovePackageService.ListPackageVersions
   */
  listPackageVersions: {
    methodKind: "unary";
    input: typeof ListPackageVersionsRequestSchema;
    output: typeof ListPackageVersionsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_iota_grpc_v1_move_package_service, 0);

