// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// @generated by scripts/update-graphql-schemas.ts from IOTA node 1.33.0, do not edit

import { initGraphQLTada } from 'gql.tada';

import type { introspection } from '../../generated/latest/tada-env.js';
import type { CustomScalars } from '../../types.js';

export * from '../../types.js';

export type { FragmentOf, ResultOf, VariablesOf, TadaDocumentNode } from 'gql.tada';
export { readFragment, maskFragments } from 'gql.tada';

export const graphql = initGraphQLTada<{
    introspection: introspection;
    scalars: CustomScalars;
}>();
