// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

import { existsSync } from 'node:fs';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path, { resolve } from 'node:path';
import TOML from '@iarna/toml';
import {
    createSchemaTsConfigFile,
    generateSchema,
    createSchemaIndexFile,
    addExportsToPackageJson,
} from './generate-schema-lib.js';

const LATEST = 'latest';

// a schema version: the `MAJOR.MINOR.PATCH` release of the iota node, e.g. `1.33.0`
const SCHEMA_VERSION = /^\d+\.\d+\.\d+$/;

// comment in each index file with the node version its schema was generated from
function generatedComment(nodeVersion: string) {
    return `// @generated by scripts/update-graphql-schemas.ts from IOTA node ${nodeVersion}, do not edit`;
}
const GENERATED_VERSION_LINE = /^\/\/ @generated .* from IOTA node (\S+),/m;

const packageRoot = path.resolve(import.meta.url.slice(5), '../..');
const workspaceRoot = path.resolve(packageRoot, '../..');
const schemaSourceFilePath = path.resolve(
    workspaceRoot,
    'external/iota/crates/iota-graphql-rpc',
    'schema.graphql',
);
const nodeCargoTomlPath = path.resolve(workspaceRoot, 'external/iota/Cargo.toml');
const latestSchemaPath = path.resolve(
    packageRoot,
    `src/graphql/generated/${LATEST}/schema.graphql`,
);

// creates the stub package.json used by resolvers that don't support the `exports` field
async function createSchemaStubPackageJson(name: string) {
    const stubFolder = resolve(packageRoot, `graphql/schemas/${name}/`);
    await mkdir(stubFolder, { recursive: true });

    const stub = {
        private: true,
        import: `../../../dist/esm/graphql/schemas/${name}/index.js`,
        main: `../../../dist/cjs/graphql/schemas/${name}/index.js`,
        sideEffects: false,
    };

    await writeFile(resolve(stubFolder, 'package.json'), `${JSON.stringify(stub, null, '    ')}\n`);
}

function schemaIndexPath(name: string) {
    return resolve(packageRoot, `src/graphql/schemas/${name}/index.ts`);
}

// writes a schema version from a schema file: schema, types, stub, export and index. The index is
// removed first and written last, so a schema version without an index is an interrupted write.
async function writeSchemaVersion(name: string, sourceSchemaPath: string, nodeVersion: string) {
    const targetFolderGenerated = resolve(packageRoot, `src/graphql/generated/${name}/`);
    const targetFolderSchemas = resolve(packageRoot, `src/graphql/schemas/${name}/`);

    await rm(schemaIndexPath(name), { force: true });
    await mkdir(targetFolderGenerated, { recursive: true });
    await mkdir(targetFolderSchemas, { recursive: true });
    await copyFile(sourceSchemaPath, resolve(targetFolderGenerated, 'schema.graphql'));

    await createSchemaTsConfigFile(targetFolderGenerated, name);
    await generateSchema(targetFolderGenerated);
    await createSchemaStubPackageJson(name);
    await addExportsToPackageJson(packageRoot, [name]);
    await createSchemaIndexFile(targetFolderSchemas, name, generatedComment(nodeVersion));
}

// checks whether `latest` was fully written from the node schema
async function isLatestUpToDate(latestVersion: string | undefined) {
    return (
        latestVersion !== undefined &&
        existsSync(latestSchemaPath) &&
        (await readFile(schemaSourceFilePath, 'utf-8')) ===
            (await readFile(latestSchemaPath, 'utf-8'))
    );
}

// compares two `MAJOR.MINOR.PATCH` schema versions
function compareSchemaVersions(a: string, b: string) {
    const [partsA, partsB] = [a, b].map((version) => version.split('.').map(Number));

    return partsA.map((part, i) => part - partsB[i]).find((diff) => diff !== 0) ?? 0;
}

// checks that a version is a `MAJOR.MINOR.PATCH` schema version
function assertSchemaVersion(
    version: string | undefined,
    source: string,
): asserts version is string {
    if (!version || !SCHEMA_VERSION.test(version)) {
        throw new Error(`Invalid GraphQL schema version "${version ?? ''}" in ${source}`);
    }
}

// reads the iota version in the submodule, without its prerelease suffix (e.g. `-alpha`)
async function readNodeVersion() {
    const cargoToml = TOML.parse(await readFile(nodeCargoTomlPath, 'utf-8')) as {
        workspace?: { package?: { version?: string } };
    };
    const version = cargoToml.workspace?.package?.version?.split('-')[0];
    assertSchemaVersion(version, nodeCargoTomlPath);

    return version;
}

// reads the node version of `latest` from its index file, if `latest` exists
async function readLatestVersion() {
    const latestIndexPath = schemaIndexPath(LATEST);
    if (!existsSync(latestIndexPath)) {
        return undefined;
    }

    const version = (await readFile(latestIndexPath, 'utf-8')).match(GENERATED_VERSION_LINE)?.[1];
    assertSchemaVersion(version, latestIndexPath);

    return version;
}

// `latest` follows the node schema in the submodule. A schema change in a new node version freezes
// the old `latest` under its version.
const newLatestVersion = await readNodeVersion();
const oldLatestVersion = await readLatestVersion();

// 1. check whether the node version and the node schema have changed
const hasNewVersion = oldLatestVersion !== undefined && newLatestVersion !== oldLatestVersion;
const hasNewSchema = !(await isLatestUpToDate(oldLatestVersion));

// frozen schema versions are published, so an older node version must not replace a newer `latest`
if (hasNewVersion && compareSchemaVersions(newLatestVersion, oldLatestVersion) < 0) {
    throw new Error(
        `iota node ${newLatestVersion} is older than ${LATEST} (${oldLatestVersion}), check out a newer node in the submodule`,
    );
}

if (!hasNewSchema) {
    console.log(
        `GraphQL schema of iota node ${newLatestVersion} is unchanged, ${LATEST} (${oldLatestVersion}) is up to date`,
    );
} else {
    // 2. a new node version freezes the old latest
    if (hasNewVersion) {
        await writeSchemaVersion(oldLatestVersion, latestSchemaPath, oldLatestVersion);
    }

    // 3. update `latest` and store its node version
    await writeSchemaVersion(LATEST, schemaSourceFilePath, newLatestVersion);

    console.log(
        hasNewVersion
            ? `Froze GraphQL schema ${oldLatestVersion} and updated ${LATEST} to ${newLatestVersion}`
            : `Updated ${LATEST} (${newLatestVersion}) with the new GraphQL schema`,
    );
}
