// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 3
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'iotawallet';

export const ApiKey: Record<Environment, string> = {
    iotawallet: '2a5d35822a1bab41835813f0223f319e',
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
    plan: {
        version: '3',
        branch: 'main',
        source: 'web',
        versionId: '41c28342-e260-4c3e-8465-6618203f115a',
    },
    ...{
        ingestionMetadata: {
            sourceName: 'browser-typescript-ampli',
            sourceVersion: '2.0.0',
        },
    },
    serverZone: amplitude.Types.ServerZone.EU,
};

export interface LoadOptionsBase {
    disabled?: boolean;
}

export type LoadOptionsWithEnvironment = LoadOptionsBase & {
    environment: Environment;
    client?: { configuration?: BrowserOptions };
};
export type LoadOptionsWithApiKey = LoadOptionsBase & {
    client: { apiKey: string; configuration?: BrowserOptions };
};
export type LoadOptionsWithClientInstance = LoadOptionsBase & {
    client: { instance: BrowserClient };
};

export type LoadOptions =
    | LoadOptionsWithEnvironment
    | LoadOptionsWithApiKey
    | LoadOptionsWithClientInstance;

export interface IdentifyProperties {
    network?: string;
}

export interface AddedAccountsProperties {
    accountOrigin?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
    isFirstAccount?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    numberOfAccounts?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ChangedSidePanelProperties {
    enabled: boolean;
}

export interface ChangedThemeProperties {
    theme: string;
}

export interface ClickedAppsBannerCtaProperties {
    bannerUrl?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ClickedCollectibleCardProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface ClickedCreateNewAccountProperties {
    accountOrigin?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
    isFirstAccount?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ClickedHideAssetProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface ClickedShowAssetProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface ClickedStakeIotaProperties {
    isCurrentlyStaking?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ClickedUnstakeIotaProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    stakedAmount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
}

export interface CopiedElementProperties {
    type?: string;
    value?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | private, public |
     */
    visibility?: 'private' | 'public';
}

export interface DeletedAccountProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
}

export interface DisconnectedApplicationProperties {
    applicationName?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    disconnectedAccounts?: number;
    partial?: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    sourceFlow?: string;
}

export interface ExportedAccountKeysProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
}

export interface OpenedApplicationProperties {
    applicationName?: string;
}

export interface OpenedLinkProperties {
    type?: string;
    value?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | private, public |
     */
    visibility?: 'private' | 'public';
}

export interface OpenedTransactionProperties {
    success?: boolean;
    transactionType?: string;
}

export interface PinnedCoinProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
}

export interface RespondedToConnectionRequestProperties {
    applicationName?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
    approvedConnection?: boolean;
}

export interface RespondedToTransactionRequestProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
    approvedTransaction?: boolean;
    receivedFailureWarning?: boolean;
}

export interface SelectedCoinProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    totalBalance?: number;
}

export interface SelectedValidatorProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    validatorAPY?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorName?: string;
}

export interface SentCoinsProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    amount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
}

export interface SentCollectibleProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    collectibleType?: string;
}

export interface StakedIotaProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    stakedAmount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    validatorAPY?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorName?: string;
}

export interface StartedDappConnectionProperties {
    applicationName?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    applicationUrl?: string;
}

export interface SwitchedNetworkProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    toNetwork?: string;
}

export interface UnpinnedCoinProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    coinType?: string;
}

export interface UnstakedIotaProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    rewards?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    stakedAmount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorAddress?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    validatorName?: string;
}

export interface UpdatedAutoLockProperties {
    autoLock: boolean;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    lockTimeSeconds: number;
}

export interface UsedBalanceFinderProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Regex |  |
     */
    accountType?: string;
}

export class Identify implements BaseEvent {
    event_type = amplitude.Types.SpecialEventType.IDENTIFY;

    constructor(public event_properties?: IdentifyProperties) {
        this.event_properties = event_properties;
    }
}

export class AddedAccounts implements BaseEvent {
    event_type = 'added accounts';

    constructor(public event_properties?: AddedAccountsProperties) {
        this.event_properties = event_properties;
    }
}

export class ChangedSidePanel implements BaseEvent {
    event_type = 'changed side panel';

    constructor(public event_properties: ChangedSidePanelProperties) {
        this.event_properties = event_properties;
    }
}

export class ChangedTheme implements BaseEvent {
    event_type = 'changed theme';

    constructor(public event_properties: ChangedThemeProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedAppsBannerCta implements BaseEvent {
    event_type = 'clicked apps banner cta';

    constructor(public event_properties?: ClickedAppsBannerCtaProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedCollectibleCard implements BaseEvent {
    event_type = 'clicked collectible card';

    constructor(public event_properties?: ClickedCollectibleCardProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedCreateNewAccount implements BaseEvent {
    event_type = 'clicked create new account';

    constructor(public event_properties?: ClickedCreateNewAccountProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedHideAsset implements BaseEvent {
    event_type = 'clicked hide asset';

    constructor(public event_properties?: ClickedHideAssetProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedShowAsset implements BaseEvent {
    event_type = 'clicked show asset';

    constructor(public event_properties?: ClickedShowAssetProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedStakeIota implements BaseEvent {
    event_type = 'clicked stake IOTA';

    constructor(public event_properties?: ClickedStakeIotaProperties) {
        this.event_properties = event_properties;
    }
}

export class ClickedUnstakeIota implements BaseEvent {
    event_type = 'clicked unstake IOTA';

    constructor(public event_properties?: ClickedUnstakeIotaProperties) {
        this.event_properties = event_properties;
    }
}

export class CopiedElement implements BaseEvent {
    event_type = 'copied element';

    constructor(public event_properties?: CopiedElementProperties) {
        this.event_properties = event_properties;
    }
}

export class DeletedAccount implements BaseEvent {
    event_type = 'deleted account';

    constructor(public event_properties?: DeletedAccountProperties) {
        this.event_properties = event_properties;
    }
}

export class DisconnectedApplication implements BaseEvent {
    event_type = 'disconnected application';

    constructor(public event_properties?: DisconnectedApplicationProperties) {
        this.event_properties = event_properties;
    }
}

export class ExportedAccountKeys implements BaseEvent {
    event_type = 'exported account keys';

    constructor(public event_properties?: ExportedAccountKeysProperties) {
        this.event_properties = event_properties;
    }
}

export class OpenedApplication implements BaseEvent {
    event_type = 'opened application';

    constructor(public event_properties?: OpenedApplicationProperties) {
        this.event_properties = event_properties;
    }
}

export class OpenedLink implements BaseEvent {
    event_type = 'opened link';

    constructor(public event_properties?: OpenedLinkProperties) {
        this.event_properties = event_properties;
    }
}

export class OpenedTransaction implements BaseEvent {
    event_type = 'opened transaction';

    constructor(public event_properties?: OpenedTransactionProperties) {
        this.event_properties = event_properties;
    }
}

export class PinnedCoin implements BaseEvent {
    event_type = 'pinned coin';

    constructor(public event_properties?: PinnedCoinProperties) {
        this.event_properties = event_properties;
    }
}

export class RenamedAccount implements BaseEvent {
    event_type = 'renamed account';
}

export class ResetWallet implements BaseEvent {
    event_type = 'reset wallet';
}

export class RespondedToConnectionRequest implements BaseEvent {
    event_type = 'responded to connection request';

    constructor(public event_properties?: RespondedToConnectionRequestProperties) {
        this.event_properties = event_properties;
    }
}

export class RespondedToTransactionRequest implements BaseEvent {
    event_type = 'responded to transaction request';

    constructor(public event_properties?: RespondedToTransactionRequestProperties) {
        this.event_properties = event_properties;
    }
}

export class SelectedCoin implements BaseEvent {
    event_type = 'selected coin';

    constructor(public event_properties?: SelectedCoinProperties) {
        this.event_properties = event_properties;
    }
}

export class SelectedValidator implements BaseEvent {
    event_type = 'selected validator';

    constructor(public event_properties?: SelectedValidatorProperties) {
        this.event_properties = event_properties;
    }
}

export class SentCoins implements BaseEvent {
    event_type = 'sent coins';

    constructor(public event_properties?: SentCoinsProperties) {
        this.event_properties = event_properties;
    }
}

export class SentCollectible implements BaseEvent {
    event_type = 'sent collectible';

    constructor(public event_properties?: SentCollectibleProperties) {
        this.event_properties = event_properties;
    }
}

export class StakedIota implements BaseEvent {
    event_type = 'staked IOTA';

    constructor(public event_properties?: StakedIotaProperties) {
        this.event_properties = event_properties;
    }
}

export class StartedDappConnection implements BaseEvent {
    event_type = 'started dapp connection';

    constructor(public event_properties?: StartedDappConnectionProperties) {
        this.event_properties = event_properties;
    }
}

export class SwitchedNetwork implements BaseEvent {
    event_type = 'switched network';

    constructor(public event_properties?: SwitchedNetworkProperties) {
        this.event_properties = event_properties;
    }
}

export class UnpinnedCoin implements BaseEvent {
    event_type = 'unpinned coin';

    constructor(public event_properties?: UnpinnedCoinProperties) {
        this.event_properties = event_properties;
    }
}

export class UnstakedIota implements BaseEvent {
    event_type = 'unstaked IOTA';

    constructor(public event_properties?: UnstakedIotaProperties) {
        this.event_properties = event_properties;
    }
}

export class UpdatedAutoLock implements BaseEvent {
    event_type = 'updated auto lock';

    constructor(public event_properties: UpdatedAutoLockProperties) {
        this.event_properties = event_properties;
    }
}

export class UsedBalanceFinder implements BaseEvent {
    event_type = 'used balance finder';

    constructor(public event_properties?: UsedBalanceFinderProperties) {
        this.event_properties = event_properties;
    }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param properties The user properties.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    properties?: IdentifyProperties,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        amplitudeIdentify.set(key, value);
      }
    }
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * added accounts
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/added%20accounts)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountOrigin)
   * @param options Amplitude event options.
   */
  addedAccounts(
    properties?: AddedAccountsProperties,
    options?: EventOptions,
  ) {
    return this.track(new AddedAccounts(properties), options);
  }

  /**
   * changed side panel
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/changed%20side%20panel)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. enabled)
   * @param options Amplitude event options.
   */
  changedSidePanel(
    properties: ChangedSidePanelProperties,
    options?: EventOptions,
  ) {
    return this.track(new ChangedSidePanel(properties), options);
  }

  /**
   * changed theme
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/changed%20theme)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. theme)
   * @param options Amplitude event options.
   */
  changedTheme(
    properties: ChangedThemeProperties,
    options?: EventOptions,
  ) {
    return this.track(new ChangedTheme(properties), options);
  }

  /**
   * clicked apps banner cta
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20apps%20banner%20cta)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. bannerUrl)
   * @param options Amplitude event options.
   */
  clickedAppsBannerCta(
    properties?: ClickedAppsBannerCtaProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedAppsBannerCta(properties), options);
  }

  /**
   * clicked collectible card
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20collectible%20card)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  clickedCollectibleCard(
    properties?: ClickedCollectibleCardProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedCollectibleCard(properties), options);
  }

  /**
   * clicked create new account
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20create%20new%20account)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountOrigin)
   * @param options Amplitude event options.
   */
  clickedCreateNewAccount(
    properties?: ClickedCreateNewAccountProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedCreateNewAccount(properties), options);
  }

  /**
   * clicked hide asset
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20hide%20asset)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  clickedHideAsset(
    properties?: ClickedHideAssetProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedHideAsset(properties), options);
  }

  /**
   * clicked show asset
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20show%20asset)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  clickedShowAsset(
    properties?: ClickedShowAssetProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedShowAsset(properties), options);
  }

  /**
   * clicked stake IOTA
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20stake%20IOTA)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. isCurrentlyStaking)
   * @param options Amplitude event options.
   */
  clickedStakeIota(
    properties?: ClickedStakeIotaProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedStakeIota(properties), options);
  }

  /**
   * clicked unstake IOTA
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/clicked%20unstake%20IOTA)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. stakedAmount)
   * @param options Amplitude event options.
   */
  clickedUnstakeIota(
    properties?: ClickedUnstakeIotaProperties,
    options?: EventOptions,
  ) {
    return this.track(new ClickedUnstakeIota(properties), options);
  }

  /**
   * copied element
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/copied%20element)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. type)
   * @param options Amplitude event options.
   */
  copiedElement(
    properties?: CopiedElementProperties,
    options?: EventOptions,
  ) {
    return this.track(new CopiedElement(properties), options);
  }

  /**
   * deleted account
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/deleted%20account)
   *
   * Fires when the user clicks on the “Delete” option on one of his accounts.
   *
   * @param properties The event's properties (e.g. accountType)
   * @param options Amplitude event options.
   */
  deletedAccount(
    properties?: DeletedAccountProperties,
    options?: EventOptions,
  ) {
    return this.track(new DeletedAccount(properties), options);
  }

  /**
   * disconnected application
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/disconnected%20application)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  disconnectedApplication(
    properties?: DisconnectedApplicationProperties,
    options?: EventOptions,
  ) {
    return this.track(new DisconnectedApplication(properties), options);
  }

  /**
   * exported account keys
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/exported%20account%20keys)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountType)
   * @param options Amplitude event options.
   */
  exportedAccountKeys(
    properties?: ExportedAccountKeysProperties,
    options?: EventOptions,
  ) {
    return this.track(new ExportedAccountKeys(properties), options);
  }

  /**
   * opened application
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/opened%20application)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  openedApplication(
    properties?: OpenedApplicationProperties,
    options?: EventOptions,
  ) {
    return this.track(new OpenedApplication(properties), options);
  }

  /**
   * opened link
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/opened%20link)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. type)
   * @param options Amplitude event options.
   */
  openedLink(
    properties?: OpenedLinkProperties,
    options?: EventOptions,
  ) {
    return this.track(new OpenedLink(properties), options);
  }

  /**
   * opened transaction
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/opened%20transaction)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. success)
   * @param options Amplitude event options.
   */
  openedTransaction(
    properties?: OpenedTransactionProperties,
    options?: EventOptions,
  ) {
    return this.track(new OpenedTransaction(properties), options);
  }

  /**
   * pinned coin
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/pinned%20coin)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. coinType)
   * @param options Amplitude event options.
   */
  pinnedCoin(
    properties?: PinnedCoinProperties,
    options?: EventOptions,
  ) {
    return this.track(new PinnedCoin(properties), options);
  }

  /**
   * renamed account
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/renamed%20account)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  renamedAccount(
    options?: EventOptions,
  ) {
    return this.track(new RenamedAccount(), options);
  }

  /**
   * reset wallet
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/reset%20wallet)
   *
   * Event has no description in tracking plan.
   *
   * @param options Amplitude event options.
   */
  resetWallet(
    options?: EventOptions,
  ) {
    return this.track(new ResetWallet(), options);
  }

  /**
   * responded to connection request
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/responded%20to%20connection%20request)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  respondedToConnectionRequest(
    properties?: RespondedToConnectionRequestProperties,
    options?: EventOptions,
  ) {
    return this.track(new RespondedToConnectionRequest(properties), options);
  }

  /**
   * responded to transaction request
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/responded%20to%20transaction%20request)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationUrl)
   * @param options Amplitude event options.
   */
  respondedToTransactionRequest(
    properties?: RespondedToTransactionRequestProperties,
    options?: EventOptions,
  ) {
    return this.track(new RespondedToTransactionRequest(properties), options);
  }

  /**
   * selected coin
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/selected%20coin)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. coinType)
   * @param options Amplitude event options.
   */
  selectedCoin(
    properties?: SelectedCoinProperties,
    options?: EventOptions,
  ) {
    return this.track(new SelectedCoin(properties), options);
  }

  /**
   * selected validator
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/selected%20validator)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. validatorAddress)
   * @param options Amplitude event options.
   */
  selectedValidator(
    properties?: SelectedValidatorProperties,
    options?: EventOptions,
  ) {
    return this.track(new SelectedValidator(properties), options);
  }

  /**
   * sent coins
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/sent%20coins)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. amount)
   * @param options Amplitude event options.
   */
  sentCoins(
    properties?: SentCoinsProperties,
    options?: EventOptions,
  ) {
    return this.track(new SentCoins(properties), options);
  }

  /**
   * sent collectible
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/sent%20collectible)
   *
   * This event need to join with `collectible sent` later
   *
   * @param properties The event's properties (e.g. collectibleType)
   * @param options Amplitude event options.
   */
  sentCollectible(
    properties?: SentCollectibleProperties,
    options?: EventOptions,
  ) {
    return this.track(new SentCollectible(properties), options);
  }

  /**
   * staked IOTA
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/staked%20IOTA)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. stakedAmount)
   * @param options Amplitude event options.
   */
  stakedIota(
    properties?: StakedIotaProperties,
    options?: EventOptions,
  ) {
    return this.track(new StakedIota(properties), options);
  }

  /**
   * started dapp connection
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/started%20dapp%20connection)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. applicationName)
   * @param options Amplitude event options.
   */
  startedDappConnection(
    properties?: StartedDappConnectionProperties,
    options?: EventOptions,
  ) {
    return this.track(new StartedDappConnection(properties), options);
  }

  /**
   * switched network
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/switched%20network)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. toNetwork)
   * @param options Amplitude event options.
   */
  switchedNetwork(
    properties?: SwitchedNetworkProperties,
    options?: EventOptions,
  ) {
    return this.track(new SwitchedNetwork(properties), options);
  }

  /**
   * unpinned coin
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/unpinned%20coin)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. coinType)
   * @param options Amplitude event options.
   */
  unpinnedCoin(
    properties?: UnpinnedCoinProperties,
    options?: EventOptions,
  ) {
    return this.track(new UnpinnedCoin(properties), options);
  }

  /**
   * unstaked IOTA
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/unstaked%20IOTA)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. rewards)
   * @param options Amplitude event options.
   */
  unstakedIota(
    properties?: UnstakedIotaProperties,
    options?: EventOptions,
  ) {
    return this.track(new UnstakedIota(properties), options);
  }

  /**
   * updated auto lock
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/updated%20auto%20lock)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. autoLock)
   * @param options Amplitude event options.
   */
  updatedAutoLock(
    properties: UpdatedAutoLockProperties,
    options?: EventOptions,
  ) {
    return this.track(new UpdatedAutoLock(properties), options);
  }

  /**
   * used balance finder
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Wallet/events/main/latest/used%20balance%20finder)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. accountType)
   * @param options Amplitude event options.
   */
  usedBalanceFinder(
    properties?: UsedBalanceFinderProperties,
    options?: EventOptions,
  ) {
    return this.track(new UsedBalanceFinder(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
