// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest)
 *
 * [Full Setup Instructions](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

import { getAmplitudeConsentStatus } from '../amplitude';

export type Environment = 'iotanames';

export const ApiKey: Record<Environment, string> = {
    iotanames: '046308c03d97539ea94cefe036142905',
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
    plan: {
        version: '1',
        branch: 'main',
        source: 'web',
        versionId: 'd1206ad7-730b-40f8-ab26-ced8dfa98962',
    },
    ...{
        ingestionMetadata: {
            sourceName: 'browser-typescript-ampli',
            sourceVersion: '2.0.0',
        },
    },
    serverZone: amplitude.Types.ServerZone.EU,
};

export interface LoadOptionsBase {
    disabled?: boolean;
}

export type LoadOptionsWithEnvironment = LoadOptionsBase & {
    environment: Environment;
    client?: { configuration?: BrowserOptions };
};
export type LoadOptionsWithApiKey = LoadOptionsBase & {
    client: { apiKey: string; configuration?: BrowserOptions };
};
export type LoadOptionsWithClientInstance = LoadOptionsBase & {
    client: { instance: BrowserClient };
};

export type LoadOptions =
    | LoadOptionsWithEnvironment
    | LoadOptionsWithApiKey
    | LoadOptionsWithClientInstance;

export interface AppliedAuctionNameFilterProperties {
    query: string;
}

export interface ConnectedAddressProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | current, external, empty |
     */
    addressType: 'current' | 'external' | 'empty';
    name: string;
    setNameAsDisplayed?: boolean;
}

export interface ConnectedWalletProperties {
    wallet: string;
}

export interface CreatedSubnameProperties {
    allowToCreateAdditionalSubnames?: boolean;
    allowToRenewExpiration?: boolean;
    name: string;
    parentName?: string;
    expirationType?: string;
    subname?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Unique Items | true |
     * | Item Type | string |
     */
    subnamePermissions?: ('allow_to_create_additional_subnames' | 'allow_to_renew_expiration')[];
}

export interface DomainClaimedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    auctionWonDate: number;
    name: string;
}

export interface OpenedIotaNamesProperties {
    activeOrigin: string;
    pagePath?: string;
    pagePathFragment?: string;
}

export interface PerformedSearchProperties {
    query: string;
}

export interface PlacedAuctionBidProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    auctionCurrentBidAmount: number;
    coinType?: string;
    isUserFirstBidOnAuction: boolean;
    name: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    userBidAmount: number;
    wasUserTopBidder: boolean;
}

export interface PurchasedNameProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    amount: number;
    coinType?: string;
    discountName?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    discountPercentage?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    expirationTime: number;
    name: string;
    /**
     * Property created as alternative of `expiration` with more readable name.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    purchaseYears?: number;
}

export interface RenewedNameProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    expirationTime: number;
    name: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    renewYears: number;
}

export interface RenewedSubnameProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    expirationTime: number;
    expirationType: string;
    name: string;
}

export interface SetAvatarProperties {
    name: string;
    setAvatar: boolean;
}

export interface SetNameAsDisplayedProperties {
    name: string;
}

export class AppliedAuctionNameFilter implements BaseEvent {
    event_type = 'applied auction name filter';

    constructor(public event_properties: AppliedAuctionNameFilterProperties) {
        this.event_properties = event_properties;
    }
}

export class ConnectedAddress implements BaseEvent {
    event_type = 'connected address';

    constructor(public event_properties: ConnectedAddressProperties) {
        this.event_properties = event_properties;
    }
}

export class ConnectedWallet implements BaseEvent {
    event_type = 'connected wallet';

    constructor(public event_properties: ConnectedWalletProperties) {
        this.event_properties = event_properties;
    }
}

export class CreatedSubname implements BaseEvent {
    event_type = 'created subname';

    constructor(public event_properties: CreatedSubnameProperties) {
        this.event_properties = event_properties;
    }
}

export class DomainClaimed implements BaseEvent {
    event_type = 'domain claimed';

    constructor(public event_properties: DomainClaimedProperties) {
        this.event_properties = event_properties;
    }
}

export class OpenedIotaNames implements BaseEvent {
    event_type = 'opened iota names';

    constructor(public event_properties: OpenedIotaNamesProperties) {
        this.event_properties = event_properties;
    }
}

export class PerformedSearch implements BaseEvent {
    event_type = 'performed search';

    constructor(public event_properties: PerformedSearchProperties) {
        this.event_properties = event_properties;
    }
}

export class PlacedAuctionBid implements BaseEvent {
    event_type = 'placed auction bid';

    constructor(public event_properties: PlacedAuctionBidProperties) {
        this.event_properties = event_properties;
    }
}

export class PurchasedName implements BaseEvent {
    event_type = 'purchased name';

    constructor(public event_properties: PurchasedNameProperties) {
        this.event_properties = event_properties;
    }
}

export class RenewedName implements BaseEvent {
    event_type = 'renewed name';

    constructor(public event_properties: RenewedNameProperties) {
        this.event_properties = event_properties;
    }
}

export class RenewedSubname implements BaseEvent {
    event_type = 'renewed subname';

    constructor(public event_properties: RenewedSubnameProperties) {
        this.event_properties = event_properties;
    }
}

export class SetAvatar implements BaseEvent {
    event_type = 'set avatar';

    constructor(public event_properties: SetAvatarProperties) {
        this.event_properties = event_properties;
    }
}

export class SetNameAsDisplayed implements BaseEvent {
    event_type = 'set name as displayed';

    constructor(public event_properties: SetNameAsDisplayedProperties) {
        this.event_properties = event_properties;
    }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    
    // NOTE don't show error if consent is not given yet.
    // Don't remove this check after `ampli pull web`
    if (getAmplitudeConsentStatus() === 'declined') return;

    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * applied auction name filter
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/applied%20auction%20name%20filter)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. query)
   * @param options Amplitude event options.
   */
  appliedAuctionNameFilter(
    properties: AppliedAuctionNameFilterProperties,
    options?: EventOptions,
  ) {
    return this.track(new AppliedAuctionNameFilter(properties), options);
  }

  /**
   * connected address
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/connected%20address)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. addressType)
   * @param options Amplitude event options.
   */
  connectedAddress(
    properties: ConnectedAddressProperties,
    options?: EventOptions,
  ) {
    return this.track(new ConnectedAddress(properties), options);
  }

  /**
   * connected wallet
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/connected%20wallet)
   *
   * Triggered at the end of a connection event, when the user successfully connected any wallet
   *
   * @param properties The event's properties (e.g. wallet)
   * @param options Amplitude event options.
   */
  connectedWallet(
    properties: ConnectedWalletProperties,
    options?: EventOptions,
  ) {
    return this.track(new ConnectedWallet(properties), options);
  }

  /**
   * created subname
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/created%20subname)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. allowToCreateAdditionalSubnames)
   * @param options Amplitude event options.
   */
  createdSubname(
    properties: CreatedSubnameProperties,
    options?: EventOptions,
  ) {
    return this.track(new CreatedSubname(properties), options);
  }

  /**
   * domain claimed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/domain%20claimed)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. auctionWonDate)
   * @param options Amplitude event options.
   */
  domainClaimed(
    properties: DomainClaimedProperties,
    options?: EventOptions,
  ) {
    return this.track(new DomainClaimed(properties), options);
  }

  /**
   * opened iota names
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/opened%20iota%20names)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. activeOrigin)
   * @param options Amplitude event options.
   */
  openedIotaNames(
    properties: OpenedIotaNamesProperties,
    options?: EventOptions,
  ) {
    return this.track(new OpenedIotaNames(properties), options);
  }

  /**
   * performed search
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/performed%20search)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. query)
   * @param options Amplitude event options.
   */
  performedSearch(
    properties: PerformedSearchProperties,
    options?: EventOptions,
  ) {
    return this.track(new PerformedSearch(properties), options);
  }

  /**
   * placed auction bid
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/placed%20auction%20bid)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. auctionCurrentBidAmount)
   * @param options Amplitude event options.
   */
  placedAuctionBid(
    properties: PlacedAuctionBidProperties,
    options?: EventOptions,
  ) {
    return this.track(new PlacedAuctionBid(properties), options);
  }

  /**
   * purchased name
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/purchased%20name)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. amount)
   * @param options Amplitude event options.
   */
  purchasedName(
    properties: PurchasedNameProperties,
    options?: EventOptions,
  ) {
    return this.track(new PurchasedName(properties), options);
  }

  /**
   * renewed name
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/renewed%20name)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. expirationTime)
   * @param options Amplitude event options.
   */
  renewedName(
    properties: RenewedNameProperties,
    options?: EventOptions,
  ) {
    return this.track(new RenewedName(properties), options);
  }

  /**
   * renewed subname
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/renewed%20subname)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. expirationTime)
   * @param options Amplitude event options.
   */
  renewedSubname(
    properties: RenewedSubnameProperties,
    options?: EventOptions,
  ) {
    return this.track(new RenewedSubname(properties), options);
  }

  /**
   * set avatar
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/set%20avatar)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  setAvatar(
    properties: SetAvatarProperties,
    options?: EventOptions,
  ) {
    return this.track(new SetAvatar(properties), options);
  }

  /**
   * set name as displayed
   *
   * [View in Tracking Plan](https://data.eu.amplitude.com/iota-foundation/IOTA%20Names/events/main/latest/set%20name%20as%20displayed)
   *
   * Event has no description in tracking plan.
   *
   * @param properties The event's properties (e.g. name)
   * @param options Amplitude event options.
   */
  setNameAsDisplayed(
    properties: SetNameAsDisplayedProperties,
    options?: EventOptions,
  ) {
    return this.track(new SetNameAsDisplayed(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
