# Copyright (c) 2026 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

subscription subscribeEvents($filter: SubscriptionEventFilter) {
    events(filter: $filter) {
        __typename
        ... on Event {
            ...RPC_EVENTS_FIELDS
        }
        ... on Lagged {
            count
        }
    }
}

subscription subscribeTransactions($filter: SubscriptionTransactionFilter) {
    transactions(filter: $filter) {
        __typename
        ... on TransactionBlock {
            effects {
                bcs
            }
        }
        ... on Lagged {
            count
        }
    }
}
