# Copyright (c) 2026 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

subscription subscribeEvents($filter: SubscriptionEventFilter, $startAfter: String) {
    events(filter: $filter, startAfter: $startAfter) {
        __typename
        ... on Event {
            ...RPC_EVENTS_FIELDS
            transactionBlock {
                digest
            }
        }
        ... on Lagged {
            count
        }
    }
}

subscription subscribeTransactions($filter: SubscriptionTransactionFilter, $startAfter: String) {
    transactions(filter: $filter, startAfter: $startAfter) {
        __typename
        ... on TransactionBlock {
            effects {
                bcs
            }
        }
        ... on Lagged {
            count
        }
    }
}
