name: TS Lint, Build, and Test

on:
  workflow_dispatch:
    inputs:
      isExplorer:
        description: Explorer
        type: boolean
        default: false
      isTypescriptSDK:
        description: TypeScript SDK
        type: boolean
        default: false
      isWallet:
        description: Wallet
        type: boolean
        default: false
      isWalletDashboard:
        description: Wallet Dashboard
        type: boolean
        default: false
      isEvmBridge:
        description: EVM Bridge
        type: boolean
        default: false
      isNamesSDK:
        description: Names SDK
        type: boolean
        default: false
      isNamesDapp:
        description: Names Dapp
        type: boolean
        default: false
      isNamesDisplay:
        description: Names Display
        type: boolean
        default: false
  workflow_call:
    inputs:
      isExplorer:
        type: boolean
        required: true
      isTypescriptSDK:
        type: boolean
        required: true
      isWallet:
        type: boolean
        required: true
      isWalletDashboard:
        type: boolean
        required: true
      isEvmBridge:
        type: boolean
        required: true
      isNamesSDK:
        type: boolean
        required: true
      isNamesDapp:
        type: boolean
        required: true
      isNamesDisplay:
        type: boolean
        required: true
    secrets:
      EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK:
        required: true
      EVM_BRIDGE_CONFIG:
        required: true

concurrency:
  group: turbo-build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  build:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    if: inputs.isExplorer || inputs.isTypescriptSDK || inputs.isWallet || inputs.isWalletDashboard || inputs.isEvmBridge || inputs.isNamesSDK || inputs.isNamesDapp || inputs.isNamesDisplay
    env:
      VITE_EVM_BRIDGE_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
      VITE_EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
      NEXT_PUBLIC_NAMES_DAPP_DEFAULT_NETWORK: "devnet"
      NEXT_PUBLIC_NAMES_DAPP_CONFIG: |
        {
          "devnet":{
              "network": "devnet",
              "namesDisplayUrl": "http://localhost",
              "indexerUrl": "http://localhost:3030",
              "baseUrl": "http://localhost:3005"
          }
        }
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Manypkg Check
        run: pnpm manypkg check
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - name: Lint
        run: pnpm turbo lint
      - name: Build
        run: pnpm turbo build
      - name: Test
        # @iota/ledgerjs-hw-app-iota is tested separately
        run: pnpm turbo test --filter '!@iota/ledgerjs-hw-app-iota'
      # Pack wallet extension and upload it as an artifact for easy developer use:
      - name: Wallet Extension Has Changes?
        id: wallet-diff
        continue-on-error: true
        run: pnpm dlx turbo-ignore iota-wallet
      - name: Wallet Extension Preview Package
        if: steps.wallet-diff.outcome == 'failure'
        run: pnpm --filter iota-wallet pack:zip
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: steps.wallet-diff.outcome == 'failure'
        with:
          name: wallet-extension
          path: apps/wallet/web-ext-artifacts/*
          if-no-files-found: error
          retention-days: 7

  build-cancel:
    needs: [build]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow run
        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
