name: Report CI failure to Slack

on:
  workflow_run:
    workflows: ["Turborepo Nightly checks"]
    types: [completed]

jobs:
  on-failure:
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out'
    uses: ./.github/workflows/_slack_notify.yml
    secrets: inherit
    with:
      status: failure
      title: "${{ github.event.workflow_run.name }} ${{ github.event.workflow_run.conclusion }} on ${{ github.event.workflow_run.head_branch }}"
      message: "${{ github.event.workflow_run.name }} ${{ github.event.workflow_run.conclusion }}. Author: ${{ github.event.workflow_run.head_commit.author.name }}. View failure: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
      footer: "${{ github.event.workflow_run.display_title }} ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.workflow_run.head_commit.id }}"

