name: Production Testnet Deploy for IOTA Names

on:
  workflow_dispatch:

jobs:
  deploy-testnet-production:
    uses: ./.github/workflows/vercel_app_deploy.yml
    with:
      VERCEL_ENVIRONMENT: production-testnet
      NAMES_DAPP_DEFAULT_NETWORK: testnet
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.IOTA_NAMES_VERCEL_PROJECT_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
      NAMES_DAPP_CONFIG: ${{ secrets.NAMES_DAPP_CONFIG }}
      NAMES_DAPP_FORBIDDEN_LIST: ${{ secrets.NAMES_DAPP_FORBIDDEN_LIST }}
