name: Preview Deploy for IOTA Names

on:
  pull_request:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "sdk/**"
      - "apps/names/**"
      - ".github/workflows/iota_names.preview_deploy.yml"
      - ".github/workflows/vercel_app_deploy.yml"

jobs:
  deploy-preview:
    if: (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]'))
    uses: ./.github/workflows/vercel_app_deploy.yml
    with:
      VERCEL_ENVIRONMENT: preview
      NAMES_DAPP_DEFAULT_NETWORK: devnet
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.IOTA_NAMES_VERCEL_PROJECT_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
      NAMES_DAPP_CONFIG: ${{ secrets.NAMES_DAPP_CONFIG }}
      NAMES_DAPP_FORBIDDEN_LIST: ${{ secrets.NAMES_DAPP_FORBIDDEN_LIST }}
