name: Production Deploy for Names Display

on:
  workflow_dispatch:
    inputs:
      deployment:
        type: boolean
        description: "Deploy after build?"
        required: false
        default: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Private Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the short commit hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "VERSION=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/names-display/Dockerfile
          push: true
          tags: |
            ghcr.io/iotaledger/iota-names/iota-names-display:${{ env.VERSION }}
            ghcr.io/iotaledger/iota-names/iota-names-display:latest
          no-cache: true

      - name: Add SSH key
        if: ${{ github.event.inputs.deployment == 'true' }}
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.UPDATER_SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        if: ${{ github.event.inputs.deployment == 'true' }}
        run: |
          ssh -o StrictHostKeyChecking=no updater@${{ secrets.UPDATER_SSH_HOST }} "prod ${{ env.VERSION }}"
