name: Turborepo Hierarchy

on:
  push:
    branches:
      - "develop"
      - "devnet"
      - "testnet"
      - "mainnet"
      - "releases/iota-*-release"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  diff:
    runs-on: [ubuntu-latest]
    concurrency:
      group: turbo-diff-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    outputs:
      isWallet: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'iota-wallet')) }}
      isExplorer: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'iota-explorer')) }}
      isTypescriptSDK: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/iota-sdk')) }}
      isIscSDK: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/isc-sdk')) }}
      isAppsBackend: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'apps-backend')) }}
      isWalletDashboard: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'wallet-dashboard')) }}
      isGraphQlTransport: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/graphql-transport')) }}
      isEvmBridge: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'iota-evm-bridge')) }}
      isLedgerjs: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/ledgerjs-hw-app-iota')) }}
      isKiosk: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/kiosk')) }}
      isNamesSDK: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/iota-names-sdk')) }}
      isNamesDapp: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'names-dapp')) }}
      isNamesDisplay: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'names-display')) }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Detect Changes (turbo)
        uses: "./.github/actions/turbo-diffs"
        id: turbo


  build:
    if: (!cancelled() && !failure() && (github.ref_name == 'develop' || github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    needs: diff
    uses: ./.github/workflows/_build_lint_test.yml
    with:
      isAffected: ${{ needs.diff.outputs.isExplorer == 'true' || needs.diff.outputs.isTypescriptSDK == 'true' || needs.diff.outputs.isWallet == 'true' || needs.diff.outputs.isWalletDashboard == 'true' || needs.diff.outputs.isEvmBridge == 'true' || needs.diff.outputs.isNamesSDK == 'true' || needs.diff.outputs.isNamesDapp == 'true' || needs.diff.outputs.isNamesDisplay == 'true' }}
    secrets:
      EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
      EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}

  e2e:
    if: (!cancelled() && !failure() && (github.ref_name == 'develop' || github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    needs: diff
    uses: ./.github/workflows/_e2e.yml
    with:
      isNightly: false
      isRpc: ${{ needs.diff.outputs.isRpc == 'true' }}
      isWallet: ${{ needs.diff.outputs.isWallet == 'true' }}
      isExplorer: ${{ needs.diff.outputs.isExplorer == 'true' }}
      isAppsBackend: ${{ needs.diff.outputs.isAppsBackend == 'true' }}
      isTypescriptSDK: ${{ needs.diff.outputs.isTypescriptSDK == 'true' }}
      isGraphQlTransport: ${{ needs.diff.outputs.isGraphQlTransport == 'true' }}
      isWalletDashboard: ${{ needs.diff.outputs.isWalletDashboard == 'true' }}
      isEvmBridge: ${{ needs.diff.outputs.isEvmBridge == 'true' }}
      isIscSDK: ${{ needs.diff.outputs.isIscSDK == 'true' }}
      isKiosk: ${{ needs.diff.outputs.isKiosk == 'true' }}
      isNamesDapp: ${{ needs.diff.outputs.isNamesDapp == 'true' }}
      isNamesDisplay: ${{ needs.diff.outputs.isNamesDisplay == 'true' }}
      isNamesSDK: ${{ needs.diff.outputs.isNamesSDK == 'true' }}
    secrets:
      EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
      EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
