name: Turborepo Hierarchy

on:
  push:
    branches:
      - "develop"
      - "devnet"
      - "testnet"
      - "mainnet"
      - "releases/iota-*-release"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  diff:
    runs-on: [ubuntu-latest]
    concurrency:
      group: turbo-diff-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    outputs:
      isRpc: ${{ steps.diff.outputs.isRpc }}
      isTypeScriptCodegenSync: ${{ steps.diff.outputs.isTypeScriptCodegenSync }}
      isWallet: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'iota-wallet')) }}
      isExplorer: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'iota-explorer')) }}
      isTypescriptSDK: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/iota-sdk')) }}
      isIscSDK: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/isc-sdk')) }}
      isAppsBackend: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'apps-backend')) }}
      isWalletDashboard: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'wallet-dashboard')) }}
      isGraphQlTransport: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/graphql-transport')) }}
      isEvmBridge: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'iota-evm-bridge')) }}
      isLedgerjs: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/ledgerjs-hw-app-iota')) }}
      isKiosk: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/kiosk')) }}
      isNamesSDK: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), '@iota/iota-names-sdk')) }}
      isNamesDapp: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'names-dapp')) }}
      isNamesDisplay: ${{ (steps.turbo.outputs.packages && contains(fromJson(steps.turbo.outputs.packages), 'names-display')) }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Detect Changes (turbo)
        uses: "./.github/actions/turbo-diffs"
        id: turbo
      - name: Detect Changes (diff)
        uses: "./.github/actions/diffs"
        id: diff

  sync:
    name: ts-sdk sync with Node Changes
    needs: diff
    runs-on: self-hosted-x64
    concurrency:
      group: turbo-sync-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    if: (!cancelled() && !failure() && needs.diff.outputs.isTypeScriptCodegenSync == 'true' && (github.ref_name == 'develop' || github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - name: Node Sync
        run: |
          pnpm codegen
          if [ -z "$(git status --porcelain)" ]; then
            echo "No sync needed"
          else
            echo "Sync is needed! Run: 'pnpm codegen' in the root."
            git status
            exit 1
          fi

  sync-cancel:
    needs: [sync]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow run
        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

  build:
    name: Lint, Build, and Test
    needs: diff
    runs-on: self-hosted-x64
    concurrency:
      group: turbo-build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    if: (!cancelled() && !failure() && (needs.diff.outputs.isExplorer == 'true' || needs.diff.outputs.isTypescriptSDK == 'true' || needs.diff.outputs.isWallet == 'true' || needs.diff.outputs.isWalletDashboard == 'true' || needs.diff.outputs.isEvmBridge == 'true' || needs.diff.outputs.isNamesSDK == 'true' || needs.diff.outputs.isNamesDapp == 'true' || needs.diff.outputs.isNamesDisplay == 'true') && (github.ref_name == 'develop' || github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Manypkg Check
        run: pnpm manypkg check
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - name: Lint
        run: pnpm turbo lint
      - name: Install wasm-pack for mbf package
        uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa # v0.4.0
        with:
          version: "latest"
      - name: Build
        env:
          NEXT_PUBLIC_NAMES_DAPP_DEFAULT_NETWORK: "devnet"
          NEXT_PUBLIC_NAMES_DAPP_CONFIG: |
            {"devnet":{"network":"devnet","namesDisplayUrl":"http://localhost","indexerUrl":"http://localhost:3030","baseUrl":"http://localhost:3005"}}
        run: pnpm turbo build
      - name: Test
        env:
          VITE_EVM_BRIDGE_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
          VITE_EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
        # @iota/ledgerjs-hw-app-iota is tested separately
        run: pnpm turbo test --filter '!@iota/ledgerjs-hw-app-iota'
      # Pack wallet extension and upload it as an artifact for easy developer use:
      - name: Wallet Extension Has Changes?
        id: wallet-diff
        continue-on-error: true
        run: pnpm dlx turbo-ignore iota-wallet
      - name: Wallet Extension Preview Package
        if: steps.wallet-diff.outcome == 'failure'
        run: pnpm --filter iota-wallet pack:zip
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: steps.wallet-diff.outcome == 'failure'
        with:
          name: wallet-extension
          path: apps/wallet/web-ext-artifacts/*
          if-no-files-found: error
          retention-days: 7

  build-cancel:
    needs: [build]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow run
        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}

  names-sdk-test:
    name: Names SDK Tests
    needs: diff
    if: (!cancelled() && !failure() && (needs.diff.outputs.isNamesSDK == 'true' || needs.diff.outputs.isNamesDapp == 'true') && (github.ref_name == 'develop' || github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
      - name: Install IOTA using Homebrew
        run: brew install iotaledger/tap/iota
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
      - name: Do a global PNPM install
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Typecheck SDK
        run: pnpm -F @iota/iota-names-sdk typecheck
      - name: Build SDK
        run: pnpm sdk build
      - name: Prepare local network & run SDK tests
        env:
          IS_CI_JOB: true
          NETWORK: localnet
        run: |
          iota start --with-faucet --faucet-amount 100000000000000 --with-indexer --with-graphql --force-regenesis --epoch-duration-ms 120000 > /dev/null 2>&1 &
          sleep 10
          iota client --yes new-env --alias localnet --rpc http://127.0.0.1:9000 --graphql http://127.0.0.1:9125
          iota client switch --env localnet
          iota client faucet
          sleep 5
          cd scripts
          export NETWORK=localnet
          pnpm ts-node init/init.ts localnet
          pnpm ts-node tests/register-name.ts
          sleep 5
          cat ./package-info/localnet.json
          cd ../sdk/names
          VITE_IOTA_BIN="iota" pnpm test:e2e

  e2e:
    if: (!cancelled() && !failure() && (github.ref_name == 'develop' || github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    needs: diff
    uses: ./.github/workflows/_e2e.yml
    with:
      isNightly: false
      isRpc: ${{ needs.diff.outputs.isRpc == 'true' }}
      isWallet: ${{ needs.diff.outputs.isWallet == 'true' }}
      isExplorer: ${{ needs.diff.outputs.isExplorer == 'true' }}
      isAppsBackend: ${{ needs.diff.outputs.isAppsBackend == 'true' }}
      isTypescriptSDK: ${{ needs.diff.outputs.isTypescriptSDK == 'true' }}
      isGraphQlTransport: ${{ needs.diff.outputs.isGraphQlTransport == 'true' }}
      isWalletDashboard: ${{ needs.diff.outputs.isWalletDashboard == 'true' }}
      isEvmBridge: ${{ needs.diff.outputs.isEvmBridge == 'true' }}
      isIscSDK: ${{ needs.diff.outputs.isIscSDK == 'true' }}
      isKiosk: ${{ needs.diff.outputs.isKiosk == 'true' }}
      isNamesDapp: ${{ needs.diff.outputs.isNamesDapp == 'true' }}
      isNamesDisplay: ${{ needs.diff.outputs.isNamesDisplay == 'true' }}
    secrets:
      EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
      EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
